### ISSUE TITLE
Add GUI support for the ability to export a date range

### ISSUE THREAD

**Issue by shivam-tripathi** [opendatakit/briefcase#117]
The ability to export a date range is something that's in the CLI but not in the GUI. It would be great to have this feature included in GUI too.

**Comment by yanokwa** [comment]
@shivam-tripathi Is this an issue you can take a look at for the next release?

**Comment by shivam-tripathi** [comment]
@yanokwa Sure thing.

**Comment by yanokwa** [comment]
@shivam-tripathi You still interested in contributing this feature?

**Comment by shivam-tripathi** [comment]
@yanokwa I am. Just a little busy at the moment.

**Comment by yanokwa** [comment]
We have a code freeze coming up next week and I want to make sure we have time to test and review. Should we bump to the next milestone?

**Comment by shivam-tripathi** [comment]
Next week sounds too close. I am afraid we will have to bump it to the next milestone.

**Comment by yanokwa** [comment]
Hi @shivam-tripathi! We've finished the June milestone and have started work on the July milestone. Do you have any sketches of the UI you had in mind that you can share?

**Comment by yanokwa** [comment]
Hi @shivam-tripathi! Since I haven't heard, back I'm tagging this as contributor-friendly to give others a chance at it.

@daveycrockett You seem to be pretty good at adding UI-y features to Briefcase. Any interest in this one?

**Comment by daveycrockett** [comment]
Thanks for pointing this one out, @yanokwa!  I'm happy to take it on (at the risk of pigeon-holing myself!)  It will probably take me til end of next week.

**Comment by batkinson** [comment]
Hi all. I am currently supporting active data collection efforts using ODK in Equatorial Guinea. After taking a look at a few approaches, it appears that this functionality is a linchpin of sorts for an important workflow. As such, I think this would be great to incorporate, even if not perfect from the start. That workflow:

- A fairly large number of tablets are pre-loaded with forms over USB or wi-fi from home base
- Many field workers take the tablets out into communities, performs interviews, and submit forms to Aggregate upon return to home base
- An analyst pulls down new submissions daily, visualizes and corrects any mistakes when found

This last step is where briefcase's functionality is essential:

- We want all submissions sent to Aggregate to ensure they aren't stuck on an employee's machine
- We want the enable the analyst to maintain a data set that's quick and convenient to use regardless of network connectivity issues (in other words, offline)
- The analyst *will* have to make minor corrections
- We can't realistically setup Aggregate to publish to a local server for the analyst
- The analyst runs Windows and isn't command-line savvy (nor is Windows), something visual and manual is more intuitive for them
- If the user could export the latest submission records to an existing (already corrected) export, they can incrementally fix only the new submissions as the campaign continues

The workflow is almost complete. Fortunately briefcase appends when exporting the same forms multiple times. My guess is that this is because the command line export with date range attempts to support this type of workflow. However, without the ability to export a date range from the GUI, all you get when exporting multiple times is complete duplication of all submissions in the same CSV file.

Adding this functionality completes this workflow.

**Comment by lognaturel** [comment]
Thanks for describing the use case, @batkinson! That makes a lot of sense. 

We'd love to get this in the August release and @daveycrockett has something that's really close in #139! @dcbriccetti is working with him on an internal review pass. I've verified that the functionality works as you describe but would be great if you could take it for a quick spin and verify that it works for you.

**Comment by yanokwa** [comment]
Closed by #139

**Comment by batkinson** [comment]
@lognaturel we have been running a local build with this PR integrated for about a week and, so far, things appear to be working just fine. The note above was really just to clarify how important this is for at least the workflow we're using. We're pleased that this will be part of a public release soon. I am happy to take this for a spin if/when it helps.

**Comment by lognaturel** [comment]
Awesome, thanks @batkinson!
