### ISSUE TITLE
Make export date text boxes consistent with rest of UI

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#170]
In Briefcase v1.7.0-20-gbb76756, start/end date text boxes look different than say export directory. This is likely because those text boxes are from a library. 

<img width="674" alt="screen shot 2017-08-15 at 16 11 43" src="https://user-images.githubusercontent.com/32369/29340606-be920e2a-81d4-11e7-9c01-b18b9e3cccf4.png">

I think the text boxes looking the same would be a nice improvement, but I'm not sure how hard or easy this is. The first step in this issue is to confirm why export date text boxes look different and propose a fix.

**Comment by thomashhuang** [comment]
Start Date and End Date are DatePicker objects in the ExportPanel.java file. The text box itself uses JTextField, like the Export Directory field and PEM Private Key File field. However, DatePicker automatically sets the border on its JTextField. [https://github.com/LGoodDatePicker/LGoodDatePicker/blob/master/Project/src/main/java/com/github/lgooddatepicker/components/DatePicker.java](url) found at line 930 : 
`dateTextField.setMargin(new Insets(1, 3, 2, 2));
        dateTextField.setBorder(new CompoundBorder(
                new MatteBorder(1, 1, 1, 1, new Color(122, 138, 153)),
                new EmptyBorder(1, 3, 2, 2)));`
We're intializing our JTextFields with the default constructors.

**Comment by dcbriccetti** [comment]
@thomashhuang, good work. Why don’t you set the borders—and the margins—to match those of one of the JTextFields that we create (getBorder, getMargin).

**Comment by thomashhuang** [comment]
I managed to get rid of the black border, but the text box is still oversized:

<img width="628" alt="screen shot 2017-09-13 at 7 31 14 pm" src="https://user-images.githubusercontent.com/18605591/30406865-3a48ec86-98ba-11e7-82ff-12e8a55c862b.png">

setSize and setMargin are not changing the size of the JTextFields, though. Thoughts?

**Comment by dcbriccetti** [comment]
>Why don’t you set the borders—and the margins

and the margins

**Comment by dcbriccetti** [comment]
I tried setting the border and margin last night and it worked perfectly. Show your code?

**Comment by thomashhuang** [comment]
Ok, I pulled the border and margin from the PEM Private Key File field above, this is the result: 
<img width="615" alt="screen shot 2017-09-13 at 8 05 37 pm" src="https://user-images.githubusercontent.com/18605591/30407649-2332f758-98bf-11e7-97ef-26994f433933.png">

Code: 
<img width="779" alt="screen shot 2017-09-13 at 8 06 33 pm" src="https://user-images.githubusercontent.com/18605591/30407657-27e1f790-98bf-11e7-9ee7-b3309586ab28.png">

The bottom two still seem a little bit larger. The slightly darker outline is due to the fact that the top fields are not editable.

**Comment by dcbriccetti** [comment]
I’m mildly curious if you’d get anything different if you did:
`JTextField model = new JTextField();`
And used the border and margin of `model`.
But I suspect what you show in the picture will satisfy @yanokwa.
What’s with the setText in the code? Did you add that?

**Comment by thomashhuang** [comment]
@dcbriccetti, creating a new JTextField doesn't make a difference.
I added the setText so the button to bring up the calendar is more similar to the other buttons throughout the rest of the application. All other buttons are "Choose..." or "Connect..." or something similar. It occured to me that the difference in sizes won't be noticable if the button simply said "...", since the textField would extend further across the window. I'll leave that for you or @yanokwa to decide.

**Comment by dcbriccetti** [comment]
Oh, right, they say “...” now. I like what you did for consistency.

@yanokwa can jump in anytime, but I’d say let’s go with what you have, with an improvement: Create a DatePicker factory method (maybe `createDatePicker`) to encapsulate this tweaking, and its doc comment can explain the motivation and perhaps link to this issue.

**Comment by thomashhuang** [comment]
<img width="680" alt="screen shot 2017-09-13 at 9 01 58 pm" src="https://user-images.githubusercontent.com/18605591/30408809-cdb1561e-98c6-11e7-8774-58d6a740f19a.png">

Inserted this right after the constructor, works as intended.

**Comment by dcbriccetti** [comment]
Excellent!
