### ISSUE TITLE
Deprecate Aggregate 0.9.x as a pull source

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#200]
ODK Aggregate 0.9.8 was released in 2011 and according to https://opendatakit.org/downloads/download-info/odk-aggregate-v0-9-8-1/ it was downloaded some 2050 times and has been unsupported for quite some time.

I think we should remove it from the list of pull options and remove any .9.x code that would be exercised by that option.

**Comment by icemc** [comment]
@yanokwa may I look into this issue?

**Comment by yanokwa** [comment]
Sure! Use `@opendatakit-bot claim` to claim the issue. 

Please commit the changes logically (e.g. by each class) so it's easy to review and before sending in a PR be sure to carefully review the Briefcase code tree to make sure all traces of X.9 are removed. It might be in places you don't expect.

**Comment by icemc** [comment]
@opendatakit-bot  claim.

**Comment by lognaturel** [comment]
Ooh, looks like our bot friend is not so clever. I think it didn't notice this one because of the period after "claim." @icemc can you try again without the period and see if that works? The bot is new so we're still figuring it out. It should give you a nice message. I've issued a pull request to make "claim." a keyword at https://github.com/opendatakit/zulipbot/pull/2

**Comment by yanokwa** [comment]
It's definitely because of the extra space and the issue is filed at https://github.com/zulip/zulipbot/issues/123.

**Comment by icemc** [comment]
@opendatakit-bot claim
