### ISSUE TITLE
Polish the UI for consistency

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#295]
Some ideas that I have. These are up for discussion.
- [x] Remove`Forms to Pull:`, `Forms to Push:`, and `Foms to export:` and horizontal rule
- [x] Add space to column headings so when sorting you can see the column text
- [x] Export config buttons should be half as small
- [x] Last export should be resizable
- [x] Instead of `Detail` as a column header, I think `Push/Pull/Export Log` would be 
- [x] Instead of `Details...`  button, use a button with the https://material.io/icons/#ic_receipt as a font ([ic_receipt.ttf.zip](https://github.com/opendatakit/briefcase/files/1660335/ic_receipt.ttf.zip))

All the above should be verified on macOS, Windows, Ubuntu.

**Comment by ggalmazor** [comment]
> Export config buttons should be half as small
These buttons are wide only on macs... Is this still a problem after using the icon font?

**Comment by ggalmazor** [comment]
> Instead of Detail as a column header, I think Push/Pull/Export Log would be

Making this change on the Pull and Push tabs will take some time and I'm afraid of breaking things that already are working...

**Comment by yanokwa** [comment]
I'm wondering if we should hold off on this until after the release. Because it'd be nice to touch all the panels with these changes.

**Comment by ggalmazor** [comment]
I'm almost done with these

- [x] RemoveForms to Pull:, Forms to Push:, and Foms to export: and horizontal rule
- [x] Add space to column headings so when sorting you can see the column text
- [x] Last export should be resizable
- [x] Instead of Details... button, use a button with the https://material.io/icons/#ic_receipt as a font (ic_receipt.ttf.zip)
