### ISSUE TITLE
Briefcase doesn"t remove period from form's name.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#297]
#### Software versions 
Briefcase v1.8.x, Java v1.8.x, operating system,: Ubuntu, MacOS

#### Problem description
Briefcase doesn"t remove period of dots from form's name as it used to do before. In exchange it shows _______. User is able to export that form.

#### Steps to reproduce the problem
1. Pull from aggregate of odk collect form with period of dots in the name.
2. Go to push, export section and check pulled folder in your storage directory.

#### Expected behavior
Period of dots should be removed automatically and should not be visible.

**Comment by ggalmazor** [comment]
What do you mean by 'period of dots'? Can you write an example form name so that we can use exactly what you had?

**Comment by kkrawczyk123** [comment]
I tried "Form........xml". I use to test and it worked, period was removed and briefcase displayed that form as "Form.xml" but now is not any more.

**Comment by ggalmazor** [comment]
Ok, thanks!

**Comment by ggalmazor** [comment]
This issue seems to be related to #224...Before that PR, the illegal chars where "compacted" (`Forms......xml` becomes `Forms.xml`) and now they're replaced to `_` chars (`Forms_____xml`). 

Do we go as it is with the `_` or do we change it? I think that we had some good examples in favor to replacing the chars with `_`...

**Comment by lognaturel** [comment]
The _ behavior is now the intended one for consistency across all places punctuation is replaced.
