### ISSUE TITLE
Export of encrypted form failed on MacOS and Windows.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#311]
#### Software versions 
Briefcase v1.8.x, Java v1.8.x, operating system MacOs, Windows

#### Problem description
Export of encrypted form failed on MacOS and Windows. Export of the same form with the same private PEM key file succeed on Ubuntu.

#### Steps to reproduce the problem
1.Try to export encrypted form with private PEM key file.

#### Expected behavior
The form should be exported. 

#### Other information 
Form and PEM key file I used:
[encrypted-form.xml.txt](https://github.com/opendatakit/briefcase/files/1663917/encrypted-form.xml.txt)
[private-key.txt](https://github.com/opendatakit/briefcase/files/1663916/private-key.txt)

Screenshots attached:
![screen shot 2018-01-24 at 13 31 12](https://user-images.githubusercontent.com/33342488/35388011-607e7570-01d2-11e8-819a-0af69591bce6.png)
![encrypted_windows](https://user-images.githubusercontent.com/33342488/35389677-ef397c00-01d8-11e8-8a2a-6ec341db42b2.jpg)

**Comment by ggalmazor** [comment]
I'm getting that error with java versions other than **8u161-oracle,** but with the latest version, it is working for me...

**Comment by ggalmazor** [comment]
Just confirmed that it works on my mac with Java version 1.8.0_161. Could you verify?

**Comment by yanokwa** [comment]
This problem is described at the bottom of https://github.com/opendatakit/briefcase/blob/master/README.md#setting-up-your-development-environment.

If you are working with encrypted forms you may get an InvalidKeyException. This is because you do not have an unlimited crypto policy enabled in Java. 

Java 8 Update 151 or later: Set crypto.policy=unlimited in $JAVA_HOME/jre/lib/security/java.security
Java 8: Install [Unlimited Strength Policy Files 8](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) in $JAVA_HOME/jre/lib/security

**Comment by kkrawczyk123** [comment]
It worked for java 1.8.161 for both Windows and MacOs.

**Comment by yanokwa** [comment]
Closed because this is a documentation issue.
