### ISSUE TITLE
Export list is not updating correctly.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#320]
#### Software versions 
Briefcase v1.8.x, Java v1.8.x, operating system: Windows, MacOS, probably Ubuntu too

#### Problem description
Export list is not updating correctly between running and closing briefcase.

#### Steps to reproduce the problem
1. Pull forms from aggregate
2. Go to export section, they should be present there.
3. Close briefcase
4. Delete some of forms pulled before from your storage location.
5. Open briefcase and go to export list.

#### Expected behavior
Deleted forms should not be present on export list any more, but now they are.

#### Other information 
It's regression issue because on yesterday's master version export list was updating correctly.

**Comment by ggalmazor** [comment]
Just for documentation's sake, I want to write here what we discussed on Slack about this issue.

This issue has to do with the way we handle the Forms cache which is serialized to disk between launches and the way we want to read the actual forms pulled into the storage dir.

As discussed on Slack, supporting this kind of behavior (users manually removing things from the storage dir) would require reconsidering how we work with the cache and the forms on disk because we would have to invalidate the cache on launch, making it pretty useless...

The Forms cache was created to make Briefcase launch faster. Users with lots of forms were experiencing long launch times because we need to parse each form to get their names. The cache tackles this problem by storing on a pair of Maps file hashes and `BriefcaseDefinition` instances linked to each form by their filenames.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs discusion"

**Comment by ggalmazor** [comment]
@opendatakit-bot "needs discussion"

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs discussion"

**Comment by ggalmazor** [comment]
@opendatakit-bot unclaim

**Comment by yanokwa** [comment]
We don't want users messing around with the Briefcase Storage directory and there is a readme.txt file in that directory that says that. If users choose to do mess about in that directory, then I'm OK with weird things happening.

What we might want to do instead is to give users the ability to delete forms from the UI (See https://github.com/opendatakit/briefcase/issues/122).
