### ISSUE TITLE
Log in credentials are not reset so it enables you to login with invalid credentials/no credentials

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#481]
#### Software versions 
Briefcase v1.10.x, Java v1.8.x, operating system, Ubuntu, MacOS

#### Problem description
Login credentials are not reset after choosing Reset button, so it enables you to log in with invalid credentials/no credentials

#### Steps to reproduce the problem
1. Connect to the server with correct credentials
2. Reset connection
3. Configure connection again, use the same aggregate's URL but some wrong/non-existing/ no credential and click on connect button.

You are able to log in but you shouldn't as you used bad credentials.

#### Expected behavior
It shouldn't be able to log in with invalid/non-existing credentials. Credentials are not reset.

#### Other information 
If you input bad credentials in briefcase's first run you will see "wrong credentials" error. 
I know it depends on role settings on aggregate users but I didn't select the checkbox "Allow anonymous retrieval of images, audio and video data (needed for GoogleEarth balloon displays)".
With selected checkbox on aggregate, this behavior is intended.

**Comment by ggalmazor** [comment]
Just to complement what @kkrawczyk123 is saying.

Credentials are not required for pulling when the anon user has the "Data viewer" permission. Conversely, credentials are not required for pushing when the anon user has the "Data Collector" permission.

**Comment by ggalmazor** [comment]
Thanks to @kkrawczyk123's feedback I've been able to detect that a session cookie is established once Aggregate accepts some valid credentials. Using wrong credentials after that won't produce an error on Briefcase.

I'm going to study the changes to be done to ensure that there are no side-effects between consecutive requests.

**Comment by ggalmazor** [comment]
This issue has been solved in #474. Maybe we close it?

**Comment by kkrawczyk123** [comment]
I confirm it has been fixed, the issue doesn't occur anymore on the newest master, tested on all three systems.

**Comment by ggalmazor** [comment]
#736 brings back reusable connections, which makes this issue relevant again.

This is what I've been able to learn about this:
- This issue is exclusive of the interaction between Briefcase and Aggregate
  - Aggregate does a poor job of maintaining the logged user's session (one actually can't log out once they have logged in).
- Closing established connections or giving them a short time-to-live fixes the issue, but this will have important downsides:
  - In general, this will make Briefcase slower
  - For Aggregate users it could increase costs due to more IO and quota use
- Central doesn't show this issue, because user sessions are managed correctly.

#736 improves HTTP interactions by ensuring that fresh credentials will be used to establish new connections, but connections that are already established won't be affected by this. I think that this is the right way to do it, and since this issue could be fixed by fixing session management in Aggregate, I'm inclined to ignore it altogether.

**Comment by kkrawczyk123** [comment]
@ggalmazor As the issue is not reproducible for Central I am opening an issue on Aggregate.
