### ISSUE TITLE
Improve performance of export by not parsing each form instance twice

### ISSUE THREAD

**Issue by dcbriccetti** [opendatakit/briefcase#485]
#### Software versions 
Briefcase v1.10.1

#### Problem description
Export parses each form instance with kxml2 twice: once to get the submission date, and again, after sorting on those dates, to extract everything else needed. 

One way to avoid this double parsing is to use a regular expression to get the submission date, as implemented, but not thoroughly tested, [here](https://github.com/dcbriccetti/briefcase/commit/9aab75fb08a4849950acb2adfd5646ea30c2166a).

Another way is to fully parse them once and save the `Document`s in a cache that will not exhaust the heap in low-memory environments, such as in [this untested implementation](https://github.com/dcbriccetti/briefcase/commit/855adf39bba78a8d85337fb66d97ce7a64101464) using a WeakHashMap.

Another idea is to replace xkml2 with something much faster and continuing to parse twice.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs discussion"

**Comment by ggalmazor** [comment]
I think this could be also addressed indirectly by implementing a database in Briefcase to keep track of form and submission metadata. The rationale here is that it's inefficient to parse that information every time we need to export a submission. We can parse it once when saving the submission and read it many times. In fact, we're already doing that, but we're throwing away the parsed information because we have nowhere to store it.

Once we achieve that, it's not so important to be efficient because we ensure we will be doing that only once.

In any case, I think we eventually will want to replace kxml2 with something else. Do you have any candidates, @dcbriccetti?

**Comment by ggalmazor** [comment]
Closing, since export performance improvements have been implemented
