### ISSUE TITLE
Don't switch to Push tab when Pull is initiated

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#52]
#### Software versions 
Briefcase v1.4.9

#### Problem description
Sometimes, when I initiate a pull of a form, I am switched to the Push tab automatically. I haven't investigated when it happens in detail but it may be limited to the first time a form is pulled after app launch.

#### Steps to reproduce the problem
1. Select a form
1. Click 'Pull'

#### Expected behavior
The user should remain on the pull tab until explicitly switching to the push tab.

#### Other information 
Similarly, triggering a push moves the user automatically to the export tab.

**Comment by yanokwa** [comment]
This behavior also happens after an export.

**Comment by carstendev** [comment]
This problem seems to be caused by the <tt>FocusTraversalPolicy</tt> on the <tt>MainBriefcaseWindow</tt>. In both _getComponentBefore_ and _getComponentAfter_ (line 284 - 357) 
```java
tabbedPane.setSelectedIndex(nextPanel);
```
is called, to switch to the next tab, if no component is found, satisfying the following conditions.
```java
if ( comp == tabbedPane ) {
    return comp;
}

if ( comp.isVisible() && comp.isEnabled() && (!(comp instanceof JTextField) || 
((JTextField) comp).isEditable()) ) {
    return comp;
}
```
If the cancel button, wich is the component after the pull button is disabled, the conditions will evaluate to _false_, causing the tab jump.

Instead of jumping to the next tab if no component is found, keeping the focus on the last used component could be a good solution. @yanokwa @lognaturel What do you guys think?

**Comment by lognaturel** [comment]
I say go for the refactor! 😊 It seems like a fairly focused change to make that will provide benefits in the future.

**Comment by carstendev** [comment]
Okay, I´ll work on it sometime this week.

**Comment by lognaturel** [comment]
@carstendev I'll leave this issue closed since the surface problem is fixed. We'd love some refactoring if you're still up for it! 😊

**Comment by carstendev** [comment]
@lognaturel Refactoring is still a good idea, I´ll try to work on it, as soon as I´m not so swamped with work.

**Comment by lognaturel** [comment]
Of course, whenever you have time. Thanks, @carstendev!
