### ISSUE TITLE
Export media checkbox not saved on Override export configuration. 

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#580]
#### Software versions 
Briefcase v1.11.x, Java v1.x.x, operating system: Ubuntu, MacOS and Windows

#### Problem description
Export media checkbox not saved on Override export configuration. 

#### Steps to reproduce the problem
1. Uncheck "Export media files" on export tab
2. Click on individual's form override export configuration button 
3. Export media files on that windows is selected by default so click on OK button
4. Take a look on the export tab - individual's form override export configuration button remain black
5. Export that form - media should be exported but they are not
6. Go back to individual's form override export configuration an uncheck export media files and click on ok button.
7. Take a look on the export tab - individual's form override export configuration button now is green
8. Go back to individual's form override export configuration and click on clear all button
and try case: open override, uncheck, check and click ok - now override button is green and export of media works great. 

#### Expected behavior
The individual checkbox should be valid always independently on Overal Export media files on main export tab.

**Comment by ggalmazor** [comment]
Ugh, you're right :)

So, what happens is this:
- On step 3, the dialog shows the export media checkbox checked because it's the default value. 
- Clicking on OK doesn't save a custom conf with the export media conf param toggled ON, because the user didn't effectively set any custom conf.
- The proof for that is that the gear button remains black, instead of turning green
- When you return to the custom conf dialog and uncheck/check the export media checkbox, the user actually has done some action we need to record (first, disable export media, second, enable export media).

We had the same problem with the pull before export checkbox, which is presented in the custom conf dialog as a `<select>` with these options:
- Use default
- Pull before export
- Do not pull before export.

I'll prepare that to be consistent and avoid this problem.

**Comment by ggalmazor** [comment]
@opendatakit-bot unlabel "good first issue"

**Comment by ggalmazor** [comment]
@opendatakit-bot assign
