### ISSUE TITLE
question about meta group in encrypted submission manifest

### ISSUE THREAD

**Issue by MartijnR** [opendatakit/briefcase#650]
Is ODK Briefcase doing anything with this section of submission.xml manifest of an **encrypted** submission?

```xml
    <n0:meta xmlns:n0="http://openrosa.org/xforms">
        <n0:instanceID>uuid:d13dccfe-d488-45c4-947b-b41a2cb8cab1</n0:instanceID>
    </n0:meta>
```

The instanceID is already present on the rootnode `instanceID` attribute so this seems redundant.

Not including this meta groups seem to be OK, but I wanted to confirm, because I am experiencing another nasty issue, and would like to rule this out as the possible cause.

**Comment by ggalmazor** [comment]
@lognaturel and I have discussed this recently. It would be great to have her confirm the things I'm about to say:

- It turns out that modern blank forms *should* have a `meta` group with an `instanceID` field, which should have a `<bind calculate="concat('uuid:', uuid())" nodeset="/data/meta/instanceID" readonly="true()" type="string"/>` to make Collect or other clients produce a unique instanceID for every submission. 

- The `instanceID` attribute you see on the root node of every submission is added by Aggregate when you download them with Briefcase.

  - When a form has a `meta.instanceID`, Aggregate uses that one
  - When a form doesn't have a `meta.instanceID`, Aggregate makes up one

- This means that you'll probably get into duped submissions if you have a form without a `meta.instanceID`, and your workflow doesn't involve sending submissions to Aggregate.

- Even if your workflow involves Aggregate, you *can* get dupes anyway:

  - Briefcase won't be able to identify individual submissions and you'll get dupes when pulling directly from Collect

  - Aggregate will have the same problem if you push dupes with Briefcase

**Comment by MartijnR** [comment]
Great. Thanks. This clearly shows, I should pay more attention to the Collect code instead of reverse-engineering pulled encrypted submissions in Briefcase!

**Comment by lognaturel** [comment]
Sounds right to me!
