### ISSUE TITLE
Add an option to Briefcase export to remove group names in column headers.

### ISSUE THREAD

**Issue by aurdipas** [opendatakit/briefcase#671]
**Background**
When exporting a form through Briefcase, variable names (column headers of the csv file) are not simply the one specified by the user on designing the form, but the eventual groups name the variable belong to, are automatically added before the actual name given to the variable.

In complex forms, with nested groups, this could lead in very long and complex names of column headers of the exported csv file.

These complex names bring complexity in the analysis and generate headache to data managers.

The reason of generating these complex names when exporting data from Aggregate is due to the XForm specs that give the possibility to have variables with same name inside different groups.

Most ODK users use XLSForms or Build to create their forms that will not allow duplicated variable names but data managers at the end need to manually (or with a specific manipulation post export) remove the group names for analysing the data. I

[Forum Post
](https://forum.opendatakit.org/t/allow-more-control-over-variable-naming-syntax/15192/11)

**Goal**

a) Add an option to Briefcase to export without group names.

These option will work for forms that have been created with XLSForm and Build or with forms created manually (xml) without duplicated variable names.

In case of manually written xml files with duplicated variable names, a pop up could be shown to users after parsing the file, informing that due to duplicated variable names this kind of export can not be executed.

reference [Roadmap](https://github.com/opendatakit/roadmap/issues/27)

**Comment by QollinsOchieng** [comment]
Very true Aurelio. It has been an issue for a long time. Thanks!


Odhiambo Collins Ochieng
KEMRI-KISUMU
Tel: +254702344393
Email: coodhiambo@kemricdc.org or qollinsochieng@gmail.com
-------- Original message --------From: Aurelio <notifications@github.com> Date: 22/10/2018  14:38  (GMT+03:00) To: opendatakit/briefcase <briefcase@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [opendatakit/briefcase] Add an option to Briefcase export to remove group names in column headers. (#671) 
Background

When exporting a form through Briefcase, variable names (column headers of the csv file) are not simply the one specified by the user on designing the form, but the eventual groups name the variable belong to, are automatically added before the actual name given to the variable.
In complex forms, with nested groups, this could lead in very long and complex names of column headers of the exported csv file.
These complex names bring complexity in the analysis and generate headache to data managers.
The reason of generating these complex names when exporting data from Aggregate is due to the XForm specs that give the possibility to have variables with same name inside different groups.
Most ODK users use XLSForms or Build to create their forms that will not allow duplicated variable names but data managers at the end need to manually (or with a specific manipulation post export) remove the group names for analysing the data. I
Forum Post


Goal
a) Add an option to Briefcase to export without group names.
These option will work for forms that have been created with XLSForm and Build or with forms created manually (xml) without duplicated variable names.
In case of manually written xml files with duplicated variable names, a pop up could be shown to users after parsing the file, informing that due to duplicated variable names this kind of export can not be executed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opendatakit/briefcase","title":"opendatakit/briefcase","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/opendatakit/briefcase"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Add an option to Briefcase export to remove group names in column headers. (#671)"}],"action":{"name":"View Issue","url":"https://github.com/opendatakit/briefcase/issues/671"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/opendatakit/briefcase/issues/671",
"url": "https://github.com/opendatakit/briefcase/issues/671",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Add an option to Briefcase export to remove group names in column headers. (#671)",
"sections": [
{
"text": "",
"activityTitle": "**Aurelio**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@aurdipas",
"facts": [
{
"name": "Repository: ",
"value": "opendatakit/briefcase"
},
{
"name": "Issue #: ",
"value": 671
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"opendatakit/briefcase\",\n\"issueId\": 671,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"opendatakit/briefcase\",\n\"issueId\": 671\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/opendatakit/briefcase/issues/671"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 399304883\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by ggalmazor** [comment]
This is looking good. I think I can start making this change :)

I'd like to dig a little bit into the remark about dupe variable names, though:

> In case of manually written xml files with duplicated variable names, a pop up could be shown to users after parsing the file, informing that due to duplicated variable names this kind of export can not be executed.

I think the export can be done even when there are dupe names. A column's context can be deduced by its position in the CSV file i.e. looking to what other columns are near them a user can know which group they belong to.

Would it be acceptable to have a first version that always does the export and doesn't give any feedback about this?

We can always add feedback if users complain.

**Comment by ggalmazor** [comment]
Note to future Guillermo: Always use the `Model` instead of those `pair.getLeft()`

```java
  static String encodeMainValue(Model field, Pair<String, String> value) {
    return encode(
        value.getRight(),
        EMPTY_COL_WHEN_NULL_DATATYPES.contains(field.getDataType()) || value.getLeft().startsWith("meta")
    );
  }

  static String encodeRepeatValue(Pair<String, String> pair) {
    return encode(
        pair.getRight(),
        // It would be really surprising to have meta fields in a repeat. This is the original implementation, though.
        pair.getLeft().startsWith("meta") || pair.getLeft().startsWith("SET-OF")
    );
  }
```

**Comment by QollinsOchieng** [comment]
Hi All, do we have Briefcase CLI to export to JSON File?

**Comment by ggalmazor** [comment]
Not yet.

Would you export to GeoJSON with the CLI?
