### ISSUE TITLE
Feature request(?): simple XML to CSV export

### ISSUE THREAD

**Issue by joha1** [opendatakit/briefcase#734]
I'm using ODK Briefcase together with [geoODK collect](https://github.com/GeoODK/collect) on a mobile phone.

So the phone gets an XML that defines the questions for the survey and after the fieldday, there's an XML file with the days work at `F:\internal memory\geoodk\instances\My_project_name_current_date` and a bunch of JPGs, since geoODK can add pics to a survey.

What I need, is simply a human/Excel/ArcGIS readable version of the XML file and the pictures, somewhere on `C:\work\My_project\current_date`.

Now, that's what ODK Briefcase does, but I don't get it how it does it and why it does need the whole `geodk` folder from my phone. I suppose I'm just using a small portion of the things one could do with ODK collect, so I'm probably not your typical use case, but at least I'd like to understand why ODK Briefcase works like it does.

Mostly interested in:

**Is there any information besides what is in the XML file that is needed to produce the CSV file?**

Because comparing the two, it looks like a pretty straightforward *translation* from XML to CSV. Which parts of the code base are responsible for that? Because just looking at the files, it seems like I could give it a try myself (in python though...), but before I do so, I'd like to know if I'm missing something that would make this futile.

**Comment by lognaturel** [comment]
Sorry this slipped through the cracks, @joha1. In general, https://forum.opendatakit.org/ is the place to go for support and the Github repositories are for ongoing development.

You are correct that Briefcase only uses the XML files and attached media to generate an export. It's simpler to ask users to copy the full Collect directory rather than picking and choosing files.

Since this is an old issue, you've probably already solved your problems but I just wanted to let you know that you may want to consider ODK Collect over geoODK. geoODK has not been maintained for a long time whereas ODK Collect is in active development. We believe that all features from geoODK are now available in Collect.
