### ISSUE TITLE
Improve the display of project ID in Central pulling

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#749]
Instead of 
<img width="352" alt="Screen Shot 2019-06-27 at 8 59 17 PM" src="https://user-images.githubusercontent.com/32369/60316208-7a36ef80-991e-11e9-9ba8-35e2abbc51c0.png">

I think it'd be nicer to have
https://sandbox.central.opendatakit.org (Project ID: 23)

This way we match the dialog that the user saw when entering the project ID.

For bonus points, do this instead...
```
Pulling from: Central server
URL: https://sandbox.central.opendatakit.org 
Project: Project Name (ID: 1)
```
My assumption is that Central's API lets you fetch the project name.

**Comment by ggalmazor** [comment]
I'm punting on getting the project name, because it has to start before, in the configuration dialog. Users should be able to enter the Central URL and credentials (or QR, or hash, whatever we can get Central to make it easier), and then we should show a list of projects the user has access to.

That list would have a mapping from project ID to their names.
