### ISSUE TITLE
Disabled details button is clickable when Pull all forms and Cancel pulling.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#755]
#### Software versions 
Briefcase v1.16.x, Java v1.x.x, operating system, Aggregate v1.x.x, Collect v1.x.x...
not a high-priority issue

#### Problem description
Disabled details button is clickable when Pull all forms and Cancel pulling.

#### Steps to reproduce the problem
1. Log to Aggregate server
2. Click on Select All button
3. Click on Pull button
4. Click on Cancel button
5. Scroll the form list
6. Click on one of the disabled details buttons

#### Expected behavior
Disabled details buttons should not be clickable. 

#### Other information 
the gif attached:
![Peek 2019-07-02 10-40](https://user-images.githubusercontent.com/33342488/60498328-aa7fe480-9cb6-11e9-9214-55ef93933842.gif)

**Comment by mayank8318** [comment]
@kkrawczyk123 I can try solving this issue to get familiar with the codebase again. Can you provide a zip file of the forms or point me to a link so that I can download these and upload to my local aggregate server to replicate the issue? :)

**Comment by ggalmazor** [comment]
Hi  @mayank8318! Good to have you back :)

I think the best thing you could do is to pull all the forms at https://sandbox.aggregate.opendatakit.org (10 at this moment) and reduce the height of the window so that some of them overflow the bottom of the form table.

**Comment by mayank8318** [comment]
@ggalmazor okay that sounds good

**Comment by mayank8318** [comment]
I am unable to reproduce the issue. All my forms show status as "Cancelled by user" and the details button is activated and clickable

**Comment by ggalmazor** [comment]
The key to reproduce the issue is to have more forms than the ones that fit
in the scrollable area of the form table.

If you can scroll up/down the table rows, then once you finish the pul,
only the detail buttons of the visible rows.will be enabled. The others
will be clickable but greyed out.

**Comment by kkrawczyk123** [comment]
I am also able to reproduce the issue. As Guillermo mentioned above you have to  **have more forms than the ones that fit in the scrollable area of the form table.** The easiest approach would be to use Select All button, then Pull button and Cancel button, details button would be enabled in the top of the list form. Then, scroll the list of form - details buttons would be disabled but if you click on it the details window will display but it shouldn't.

**Comment by mayank8318** [comment]
@ggalmazor @kkrawczyk123 Okay finally reproduced it. This issue is happening because we are never disabling the button, just setting the color LIGHT or DARK based on the status history text as follows:
```
private void updateDetailButton(FormStatus form, JButton button) {
    button.setForeground(form.getStatusHistory().isEmpty() ? LIGHT_GRAY : DARK_GRAY);
  }
```
Since this text is present for the forms that are currently being shown as disabled I think the correct behaviour would be to show all the buttons as clickable right?

**Comment by mayank8318** [comment]
I think I have figured out why it is happening -> `private final Map<FormStatus, JButton> detailButtons = new HashMap<>();` this hashmap doesn't have all the forms, hence the colour is set only for those forms which have appeared on the screen. 

Proof -> Before selecting the forms, scroll the list once and then follow the same procedure. All the buttons will be of the proper color. As the list is scrolled this line is executed -> 
```
case TransferFormsTableView.DETAIL_BUTTON_COL:
        return detailButtons.computeIfAbsent(form, UI::buildDetailButton);
```
and so the button is added to the hashmap. So for updating the list I think, we will have to pass the whole list of forms to this class whenever an update is performed so that all the classes remain in **sync**.

**Comment by mayank8318** [comment]
@opendatakit-bot claim
